const CONFIG={apiKey:"AIzaSyB56KzqQmNesXuoQLgLEMrK9H-NOwuqEh8",authDomain:"curriculo-ddfcd.firebaseapp.com",projectId:"curriculo-ddfcd",storageBucket:"curriculo-ddfcd.firebasestorage.app",messagingSenderId:"895337192000",appId:"1:895337192000:web:20e456628871ce83679da5"};
const SDK="12.16.0";
const appSdk=await import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-app.js`);
const fs=await import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-firestore.js`);
const app=appSdk.getApps().length?appSdk.getApp():appSdk.initializeApp(CONFIG);
let db;try{db=fs.initializeFirestore(app,{experimentalAutoDetectLongPolling:true});}catch(_){db=fs.getFirestore(app);}
const $=id=>document.getElementById(id);const texto=v=>String(v??"").trim();const norm=v=>texto(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const state={items:[],selected:null};
function setConn(ok,msg){const e=$("connection");e.textContent=msg;e.className=`connection ${ok?"ok":"error"}`;}
function dateValue(v){try{const d=v?.toDate?v.toDate():new Date(v||"");return Number.isNaN(d.getTime())?new Date(0):d;}catch(_){return new Date(0);}}
function dateText(v){const d=dateValue(v);return d.getTime()?d.toLocaleString("es-EC",{dateStyle:"medium",timeStyle:"short"}):"";}
function esc(v){return texto(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function badge(e){const s=norm(e||"pendiente");const t=texto(e||"pendiente").replace(/^./,c=>c.toUpperCase());return `<span class="badge" data-state="${esc(s)}">${esc(t)}</span>`;}
async function load(){setConn(true,"Cargando…");try{const snap=await fs.getDocs(fs.collection(db,"solicitudes_usuario"));state.items=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>dateValue(b.actualizadoEn||b.creadoEn||b.creadoEnIso)-dateValue(a.actualizadoEn||a.creadoEn||a.creadoEnIso));setConn(true,"Conectado");renderList();if(state.selected){const current=state.items.find(x=>x.id===state.selected.id);if(current)selectItem(current);}}catch(e){setConn(false,"Error de conexión");$("summary").textContent=e.message;}}
function filtered(){const q=norm($("buscar").value);const status=norm($("estadoFiltro").value);return state.items.filter(x=>{if(status&&norm(x.estado)!==status)return false;if(!q)return true;return norm([x.id,x.codigo,x.usuario?.nombres,x.usuario?.cedula,x.usuario?.correo,x.carreraNombre,x.materiaNombre].join(" ")).includes(q);});}
function renderList(){const items=filtered();$("summary").textContent=`${items.length} solicitud${items.length===1?"":"es"}`;$("empty").classList.toggle("hidden",items.length>0);$("requestList").innerHTML=items.map(x=>`<button class="request ${state.selected?.id===x.id?"active":""}" data-id="${esc(x.id)}" type="button"><div class="request-row"><span class="request-code">${esc(x.codigo||x.id)}</span>${badge(x.estado)}</div><div class="request-meta">${esc(x.usuario?.nombres||"Sin nombre")} · ${esc(x.carreraNombre||"Sin carrera")}<br>${esc(x.materiaNombre||"Sin materia")} · ${esc(dateText(x.actualizadoEn||x.creadoEn||x.creadoEnIso))}</div></button>`).join("");
  $("requestList").querySelectorAll(".request").forEach(b=>b.addEventListener("click",()=>{const x=state.items.find(i=>i.id===b.dataset.id);if(x)selectItem(x);}));}
function selectItem(x){state.selected=x;$("detailEmpty").classList.add("hidden");$("detail").classList.remove("hidden");$("dEstado").textContent=texto(x.estado||"Pendiente").replace(/^./,c=>c.toUpperCase());$("dEstado").dataset.state=norm(x.estado||"pendiente");$("dCodigo").textContent=x.codigo||x.id;$("dFecha").textContent=dateText(x.actualizadoEn||x.creadoEn||x.creadoEnIso);$("dPersona").textContent=texto(x.usuario?.nombres||"—");$("dCedula").textContent=texto(x.usuario?.cedula||"—");$("dCorreo").textContent=texto(x.usuario?.correo||"—");$("dCarrera").textContent=texto(x.carreraNombre||x.carreraId||"—");$("dNivel").textContent=x.nivelNumero?`Nivel ${x.nivelNumero}`:"—";$("dMateria").textContent=texto(x.materiaNombre||x.materiaId||"—");$("dInformacion").value=texto(x.informacion);$("dObservaciones").value=texto(x.observaciones);$("dObsAdmin").value=texto(x.observacionAdministrador);msg("");renderList();}
function msg(t,error=false){const e=$("message");e.textContent=t||"";e.className=`message ${t?(error?"error":"ok"):""}`;}
function adminSnapshot(){const x=state.selected||{};return{usuario:x.usuario||{},carreraId:x.carreraId||"",carreraNombre:x.carreraNombre||"",nivelNumero:Number(x.nivelNumero||0),materiaId:x.materiaId||"",materiaNombre:x.materiaNombre||"",materiaCodigo:x.materiaCodigo||"",informacion:texto($("dInformacion").value),observaciones:texto($("dObservaciones").value)};}
async function update(fields,label){if(!state.selected)return;const buttons=document.querySelectorAll(".actions button");buttons.forEach(b=>b.disabled=true);msg("Guardando…");try{await fs.updateDoc(fs.doc(db,"solicitudes_usuario",state.selected.id),{...fields,actualizadoEn:fs.serverTimestamp()});msg(label);await load();}catch(e){msg(e.message,true);}finally{buttons.forEach(b=>b.disabled=false);}}
async function saveCorrection(){await update({informacion:texto($("dInformacion").value),observaciones:texto($("dObservaciones").value),corregidoPorAdministrador:true},"Corrección guardada. La solicitud continúa en su estado actual.");}
async function returnRequest(){const obs=texto($("dObsAdmin").value);if(!obs)return msg("Escribe la observación que debe corregir el usuario.",true);await update({estado:"devuelto",observacionAdministrador:obs,devueltoEn:fs.serverTimestamp(),informacion:texto($("dInformacion").value),observaciones:texto($("dObservaciones").value)},"Solicitud devuelta para corrección.");}
async function rejectRequest(){const obs=texto($("dObsAdmin").value);if(!obs)return msg("Escribe el motivo del rechazo.",true);await update({estado:"rechazado",observacionAdministrador:obs,rechazadoEn:fs.serverTimestamp()},"Solicitud rechazada.");}
async function approveRequest(){const snapshot=adminSnapshot();await update({estado:"aprobado",observacionAdministrador:texto($("dObsAdmin").value),aprobadoEn:fs.serverTimestamp(),datosAprobados:snapshot,informacion:snapshot.informacion,observaciones:snapshot.observaciones},"Solicitud aprobada. El usuario ya puede descargar el PDF oficial.");}
$("btnRecargar").addEventListener("click",load);$("buscar").addEventListener("input",renderList);$("estadoFiltro").addEventListener("change",renderList);$("btnGuardarCorreccion").addEventListener("click",saveCorrection);$("btnDevolver").addEventListener("click",returnRequest);$("btnRechazar").addEventListener("click",rejectRequest);$("btnAprobar").addEventListener("click",approveRequest);
await load();
